"use client";

import React from "react";
import { motion } from "framer-motion";
import Image from "next/image";

export default function TermHero() {
  // animation variants
  const fadeUp = {
    hidden: { opacity: 0, y: 40 },
    visible: (i = 1) => ({
      opacity: 1,
      y: 0,
      transition: { delay: i * 0.2, duration: 0.6, ease: "easeOut" },
    }),
  };

  return (
    <section className="relative overflow-hidden bg-gradient-to-br from-blue-80 via-white to-blue-400 py-4 px-6 sm:px-12 lg:px-20">
      <div className="flex flex-col-reverse lg:flex-row items-center justify-between gap-12 max-w-7xl mx-auto">

        <motion.div
          className="flex-1 text-center lg:text-left space-y-6"
          initial="hidden"
          animate="visible"
          variants={fadeUp}
        >
          <motion.h1
            custom={1}
            variants={fadeUp}
            className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 leading-tight"
          >
            Terms of Use / Service <span className="text-blue-700"> Mobiperform</span>
          </motion.h1>

          <motion.p
            custom={2}
            variants={fadeUp}
            className="text-gray-700 text-lg sm:text-xl max-w-2xl mx-auto lg:mx-0"
          >
            This Agreement sets forth the terms and conditions that apply to the
            access and use of the website “mobiperform.com”.
          </motion.p>

          <motion.div custom={3} variants={fadeUp} className="space-y-4 text-gray-600">
            <p>
              This document (referred to as “Agreement”) is an electronic record
              under the Information Technology Act, 2000, generated by a computer
              system and does not require any physical or digital signatures. By
              accessing this website or registering your information, you agree
              to be bound by these Terms of Use ("TOU").
            </p>
            <p>
              This Agreement, along with the Privacy Policy and Disclaimer,
              describes our relationship with you and forms a part of this TOU.
              We may modify these Terms at any time, and your continued use
              signifies acceptance of the updated Terms.
            </p>
          </motion.div>
        </motion.div>

        <motion.div
          className="flex-1 flex justify-center lg:justify-end"
          initial={{ opacity: 0, x: 60 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
        >
          <div className="relative w-64 h-64 sm:w-80 sm:h-80 lg:w-[620px] lg:h-[620px]">
            <Image
              src="/termbanner.webp"
              alt="Terms and Condition"
              height="620"
              width="620"
              className="object-contain drop-shadow-xl"
              priority
            />
         </div>
        </motion.div>
      </div>

      <div className="absolute -top-10 -left-10 w-72 h-72 bg-blue-200 rounded-full blur-3xl opacity-40" />
      <div className="absolute bottom-0 right-0 w-72 h-72 bg-blue-300 rounded-full blur-3xl opacity-30" />
    </section>
  );
}
