"use client";
import React from "react";

export default function TermsOfUse() {
  return (
    <section className="bg-gray-50 text-gray-800 py-16 sm:py-24 lg:py-32">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto space-y-4">
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-blue-600 leading-tight">
            Terms of Use / Service – Mobiperform
          </h1>
          <p className="text-gray-700 text-lg sm:text-xl">
            This Agreement sets forth the terms and conditions that apply to the
            access and use of the website "mobiperform.com".
          </p>
        </div>

        {/* Introduction */}
        <div className="space-y-4 text-gray-700">
          <p>
            This document (referred to as “Agreement”) is an electronic record
            in terms of the Information Technology Act, 2000, generated by a
            computer system and does not require any physical or digital
            signatures. By accessing this website or registering your
            information, you agree to be bound by these Terms of Use ("TOU").
          </p>
          <p>
            This Agreement, along with the Privacy Policy and Disclaimer,
            describes our relationship with you and shall be considered part of
            this TOU. We may modify these Terms at any time; your continued use
            signifies acceptance of the updated Terms.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {/* 1. Description and Acceptance of Services */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              1. Description and Acceptance of Services
            </h2>
            <p>
              We provide information about products & services, including news
              blogs in categories like Health, Technology, Education, Travel,
              Sports, Fashion, Food, etc. You agree that participation in these
              services is voluntary.
            </p>
            <p>
              Continued usage constitutes acceptance of the TOU, including
              modifications. You consent to receive communications through
              email, phone, or SMS, even if your number is on the DND/NCPR list.
            </p>
          </div>

          {/* 2. License and Website Access */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              2. License and Website Access
            </h2>
            <p>
              The company owns all legal rights, titles, and interests in the
              services, including intellectual property. You are granted a
              limited license to access the website and services, but may not
              copy, distribute, reverse engineer, or otherwise misuse the
              content.
            </p>
            <p>
              Unauthorized actions include commercial use, fraudulent
              transactions, scraping content, deep-linking without permission,
              bypassing security, and framing the website on another domain.
            </p>
          </div>

          {/* 3. Privacy Policy */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              3. Privacy Policy
            </h2>
            <p>
              By using the website, you consent to the collection and use of
              information as described in our Privacy Policy.
            </p>
          </div>

          {/* 4. Registration/Account */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              4. Your Registration / Account
            </h2>
            <p>
              You represent that you are of legal age and legally allowed to
              access services. You are responsible for maintaining the
              confidentiality of login credentials and ensuring accuracy of
              registration information.
            </p>
          </div>

          {/* 5. Eligibility */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              5. Eligibility
            </h2>
            <p>
              You confirm that you are a resident of India, above 18 years of
              age, and capable of entering into a binding contract.
            </p>
          </div>

          {/* 6. Third-Party Links */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              6. Third-Party Links
            </h2>
            <p>
              We are not responsible for content, goods, or services on
              third-party sites. Your interaction with third-party resources is
              at your own risk.
            </p>
          </div>

          {/* 7. Disclaimer of Warranty */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              7. Disclaimer of Warranty
            </h2>
            <p>
              Services are provided "as is" and "as available". We disclaim all
              warranties, express or implied, including merchantability, fitness
              for a purpose, or non-infringement. Registration is free unless
              stated otherwise.
            </p>
          </div>

          {/* 8. Limitation of Liability */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              8. Limitation of Liability
            </h2>
            <p>
              The company shall not be liable for any damages, direct or
              indirect, arising from use of services, including third-party
              services. Liability, if proven, is limited to fees paid to the
              company.
            </p>
          </div>

          {/* 9. Site-provided Email and Postings */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              9. Site-provided Email and Postings
            </h2>
            <p>
              You may post messages or communicate via the website, but must not
              share illegal, abusive, misleading, or harmful content.
              Mobiperform reserves the right to remove posts and monitor
              activity.
            </p>
          </div>

          {/* 10. Indemnity */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              10. Indemnity
            </h2>
            <p>
              You agree to indemnify and hold the company harmless from claims,
              damages, or losses resulting from your breach of these TOU or
              violation of laws or third-party rights.
            </p>
          </div>

          {/* 11. Additional Terms */}
          <div className="space-y-2">
            <h2 className="text-xl sm:text-2xl font-bold text-blue-600">
              11. Additional Terms and Conditions
            </h2>
            <p>
              The company may update policies, services, or promotional offers
              at any time. Your continued use signifies acceptance of such
              changes. You must not use services for illegal or harmful
              purposes.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
